////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2009 Xilinx, Inc.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 11.5
//  \   \         Application : xaw2verilog
//  /   /         Filename : pll.v
// /___/   /\     Timestamp : 11/16/2016 17:53:38
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: xaw2verilog -intstyle /mnt/rose/usr5/OLD/hyun/Dropbox/Experiment_TA/2016/ISE/ipcore_dir/pll.xaw -st pll.v
//Design Name: pll
//Device: xc5vlx50-1ff676
//
// Module pll
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
// For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT0 = 0.199 ns
// For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT1 = 0.151 ns
// For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT2 = 0.170 ns
`timescale 1ns / 1ps

module pll(CLKIN1_IN, 
           RST_IN, 
           CLKOUT0_OUT, 
           CLKOUT1_OUT, 
           CLKOUT2_OUT, 
           LOCKED_OUT);

    input CLKIN1_IN;
    input RST_IN;
   output CLKOUT0_OUT;
   output CLKOUT1_OUT;
   output CLKOUT2_OUT;
   output LOCKED_OUT;
   
   wire CLKFBOUT_CLKFBIN;
   wire CLKOUT0_BUF;
   wire CLKOUT1_BUF;
   wire CLKOUT2_BUF;
   wire GND_BIT;
   wire [4:0] GND_BUS_5;
   wire [15:0] GND_BUS_16;
   wire VCC_BIT;
   
   assign GND_BIT = 0;
   assign GND_BUS_5 = 5'b00000;
   assign GND_BUS_16 = 16'b0000000000000000;
   assign VCC_BIT = 1;
   BUFG CLKOUT0_BUFG_INST (.I(CLKOUT0_BUF), 
                           .O(CLKOUT0_OUT));
   BUFG CLKOUT1_BUFG_INST (.I(CLKOUT1_BUF), 
                           .O(CLKOUT1_OUT));
   BUFG CLKOUT2_BUFG_INST (.I(CLKOUT2_BUF), 
                           .O(CLKOUT2_OUT));
   PLL_ADV PLL_ADV_INST (.CLKFBIN(CLKFBOUT_CLKFBIN), 
                         .CLKINSEL(VCC_BIT), 
                         .CLKIN1(CLKIN1_IN), 
                         .CLKIN2(GND_BIT), 
                         .DADDR(GND_BUS_5[4:0]), 
                         .DCLK(GND_BIT), 
                         .DEN(GND_BIT), 
                         .DI(GND_BUS_16[15:0]), 
                         .DWE(GND_BIT), 
                         .REL(GND_BIT), 
                         .RST(RST_IN), 
                         .CLKFBDCM(), 
                         .CLKFBOUT(CLKFBOUT_CLKFBIN), 
                         .CLKOUTDCM0(), 
                         .CLKOUTDCM1(), 
                         .CLKOUTDCM2(), 
                         .CLKOUTDCM3(), 
                         .CLKOUTDCM4(), 
                         .CLKOUTDCM5(), 
                         .CLKOUT0(CLKOUT0_BUF), 
                         .CLKOUT1(CLKOUT1_BUF), 
                         .CLKOUT2(CLKOUT2_BUF), 
                         .CLKOUT3(), 
                         .CLKOUT4(), 
                         .CLKOUT5(), 
                         .DO(), 
                         .DRDY(), 
                         .LOCKED(LOCKED_OUT));
   defparam PLL_ADV_INST.BANDWIDTH = "OPTIMIZED";
   defparam PLL_ADV_INST.CLKIN1_PERIOD = 5.000;
   defparam PLL_ADV_INST.CLKIN2_PERIOD = 10.000;
   defparam PLL_ADV_INST.CLKOUT0_DIVIDE = 25;
   defparam PLL_ADV_INST.CLKOUT1_DIVIDE = 5;
   defparam PLL_ADV_INST.CLKOUT2_DIVIDE = 10;
   defparam PLL_ADV_INST.CLKOUT0_PHASE = 0.000;
   defparam PLL_ADV_INST.CLKOUT1_PHASE = 0.000;
   defparam PLL_ADV_INST.CLKOUT2_PHASE = 0.000;
   defparam PLL_ADV_INST.CLKOUT0_DUTY_CYCLE = 0.500;
   defparam PLL_ADV_INST.CLKOUT1_DUTY_CYCLE = 0.500;
   defparam PLL_ADV_INST.CLKOUT2_DUTY_CYCLE = 0.500;
   defparam PLL_ADV_INST.COMPENSATION = "INTERNAL";
   defparam PLL_ADV_INST.DIVCLK_DIVIDE = 5;
   defparam PLL_ADV_INST.CLKFBOUT_MULT = 25;
   defparam PLL_ADV_INST.CLKFBOUT_PHASE = 0.0;
   defparam PLL_ADV_INST.REF_JITTER = 0.000000;
endmodule
